### ISSUE TITLE
selection inactive bg

### ISSUE THREAD

**Issue by pwuk** [toby-j/jetbrains-github-dark-theme#1]
On the Project tree 
I Always use "Select Opened File"

It'd be useful to have 
 "selectionInactiveBackground": "#161b22",
as a differnent colour. 

It it's not visibile when clicking a file tab and the tree selects the file.

selectionBackground - would be fine (or similar)

Thanks

**Comment by toby-j** [comment]
Sure. No problem. I've been meaning to work on this some more as there's areas as you pointed out that need correcting. I've been planning to support the new UI with this theme as well, but just got to finish up with university first, only a month to go 👍

**Comment by toby-j** [comment]
Should be resolved >1.1.0
