### ISSUE TITLE
Issue with a line in the middle if of the editor window.

### ISSUE THREAD

**Issue by dew-mortal** [toby-j/jetbrains-github-dark-theme#10]
![Screenshot 2024-02-18 191913](https://github.com/toby-j/jetbrains-github-dark-theme/assets/84300371/cf116bab-5e62-4614-a618-1b773d04337e)

There is a white line in the right side of the editor window. It does not seem to have a function and is a bit distracting. Kindly fix this issue in the next update. Thanks! :)

**Comment by toby-j** [comment]
Why have I never noticed this. Looking into it now

**Comment by toby-j** [comment]
It's a setting within intellij "Show hard wrap and visual guides": https://stackoverflow.com/questions/25566070/how-to-get-rid-of-a-vertical-line-in-the-editor-pane-of-intellij-idea
