### ISSUE TITLE
bug after the last update version

### ISSUE THREAD

**Issue by leonardomarcao** [toby-j/jetbrains-github-dark-theme#11]
WTF?
![image](https://github.com/toby-j/jetbrains-github-dark-theme/assets/6151618/80de6478-bb53-4a42-bac2-99877c7401c5)

**Comment by toby-j** [comment]
Navigate to Settings -> Editor -> Color Scheme -> Scheme dropdown

IntelliJ no longer auto selects the editor theme :/

**Comment by leonardomarcao** [comment]
@toby-j Thank you so much.

This never happened to me before, but I got it.

Thanks! I love this theme <3

**Comment by sam-briggs-depop** [comment]
Also fixed my issue! Thanks!
