### ISSUE TITLE
[BUG] red rectangular block

### ISSUE THREAD

**Issue by jojoatt** [toby-j/jetbrains-github-dark-theme#2]
I noticed in IntelliJ IDEA that when using the GitHub Dark and GitHub Dark Dimmed themes, there is a red rectangular block displayed beyond the original cursor block of IntelliJ. This issue occurs in those specific themes, but not in others. 

Environment:
- IntelliJ IDEA UE: 2023.2
- System model name: MacBook Pro M1 Pro
- Os name: macOS Ventura 13.4.1
<img width="284" alt="Capture d’écran 2023-07-30 à 14 36 24" src="https://github.com/toby-j/jetbrains-github-dark-theme/assets/71399498/6eceac35-84c9-42dc-a148-a7e3dd5b852f">

Ps: This is my first issue on GitHub, so I would appreciate feedback on the issue I've raised. Please let me know if there are any missing details or additional information needed to better understand the problem or suggestion. Thank you!

**Comment by toby-j** [comment]
![image](https://github.com/toby-j/jetbrains-github-dark-theme/assets/39532961/3528cf4d-c463-4db1-b1db-c2060ce823cc)

It's the same functionality as the standard red underline as seen above. I went for the red box instead. Woud you prefer the line?

**Comment by jojoatt** [comment]
Yes, I would prefer the line. I don't know if it's possible to let the choice to the users?

**Comment by toby-j** [comment]
I'll keep it in mind, and make a decision before the next release 👍

**Comment by toby-j** [comment]
Made this change in latest
