### ISSUE TITLE
During debugging - current line boolean assessment can't be seen

### ISSUE THREAD

**Issue by u23rVa1** [toby-j/jetbrains-github-dark-theme#4]
When debugging: current line with bool comparison needs to be highlighted.
Then the boolean assessment can't be read, see screenshot.

https://prnt.sc/VRBicRzxYpAn

**Comment by toby-j** [comment]
I tried to re-create this in python and I can see the text in the box. Could you provide me a code snippit to recreate?

**Comment by toby-j** [comment]
Closing to to inactivity
