### ISSUE TITLE
Possible collision of the repo tags

### ISSUE THREAD

**Issue by albenik** [toby-j/jetbrains-github-dark-theme#7]
All tags: `1.0.0`, `1.1.1`, `1.1.2` are pointing to the same commit `b2360fe`. Is this the expected state?

<img width="1156" alt="Screenshot 2024-01-06 at 09 27 55" src="https://github.com/toby-j/jetbrains-github-dark-theme/assets/1047425/f3a2407a-bae0-42e4-8d42-2c0e1e3a8aee">

**Comment by toby-j** [comment]
No, I didn't notice. Will amend, thanks for pointing that out
